[build]
  base = "src"
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_SUPABASE_URL = "https://kpsfhtsljnjigsrmpoay.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtwc2ZodHNsam5qaWdzcm1wb2F5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMDUwODEsImV4cCI6MjA2NzU4MTA4MX0.j4jaLB5VZqel-_sFM5UoNr8yMaiSi74d-chZkZBVobY"

[context.deploy-preview.environment]
  VITE_SUPABASE_URL = "https://kpsfhtsljnjigsrmpoay.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtwc2ZodHNsam5qaWdzcm1wb2F5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMDUwODEsImV4cCI6MjA2NzU4MTA4MX0.j4jaLB5VZqel-_sFM5UoNr8yMaiSi74d-chZkZBVobY"